syntax = "proto3";

package pcbook;

option go_package = ".;pb";

import "laptop_message.proto";
import "filter_message.proto";

message CreateLaptopRequest { Laptop laptop = 1; }
message CreateLaptopResponse { string id = 1; }

message SearchLaptopRequest { Filter filter = 1; }
message SearchLaptopResponse { Laptop laptop = 1; }

service LaptopService {
  // Unary gRPC
  rpc CreateLaptop(CreateLaptopRequest) returns (CreateLaptopResponse) {};
  // Server Streaming RPC
  rpc SearchLaptop(SearchLaptopRequest) returns (stream SearchLaptopResponse) {
  };
}